[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["gym"]

[project]
name = "daggorath-gym"
version = "0.1.0"
dependencies = [
    "gymnasium>=0.28.1",
    "numpy>=1.24.0",
] 