import os

GYM_PATH = os.path.dirname(os.path.abspath(__file__))

ROOT_PATH = os.path.dirname(GYM_PATH)

EMU_PATH = os.path.join(ROOT_PATH, 'emulation')

# MAME autogenerated config — keep out of repo root
MAME_CFG_DIR = os.path.join(ROOT_PATH, '.venv', 'mame-cfg')
